### ISSUE TITLE
footnotes in the margins

### ISSUE THREAD

**Issue by cameronwp** [cameronwp/personal-web#88]
For long articles, it might make sense to move footnotes to the margins on wide displays

* Add a new `footnote-position` frontmatter option
* For phones, what happens? Leave the footnotes at the bottom? Move them under the current paragraph?

**Comment by mukki00** [comment]
should i work on YAML file or index.js file

**Comment by cameronwp** [comment]
this would be done on index.js, however, I don't think it's worth the effort for my version of the site
