### ISSUE TITLE
add bibtex entry info

### ISSUE THREAD

**Issue by cameronwp** [cameronwp/personal-web#89]
* Add a `bibtex` frontmatter option
* Add a bibtex entry to the top of any post with `bibtex: true` in the frontmatter

**Comment by cameronwp** [comment]
See https://github.com/cameronwp/hurtlingthrough.space/tree/issue-89-bibtex

**Comment by mukki00** [comment]
what's the idea of doing it? what we can see as a output @cameronwp

**Comment by cameronwp** [comment]
finally merged. see https://github.com/cameronwp/hurtlingthrough.space/pull/125
